// Replace the entire recipe data with this updated version where all images use the same consistent format
export const recipes = [
  // BREAKFAST RECIPES (5)
  {
    id: 1,
    title: "Smoked Salmon Avocado Toast",
    description:
      "Creamy avocado toast topped with smoked salmon, capers, and a squeeze of lemon. A protein-packed breakfast that's both nutritious and delicious.",
    image: "/placeholder.svg?key=ei877",
    heroImage: "/smoked-salmon-avocado-toast.png",
    time: "15 mins",
    prepTime: "15 mins",
    cookTime: "0 mins",
    difficulty: "Easy",
    servings: 2,
    tags: ["Breakfast", "Pescatarian", "High-Protein", "Quick"],
    ingredients: [
      "2 slices whole grain bread",
      "1 ripe avocado",
      "4 oz smoked salmon",
      "1 tablespoon capers, drained",
      "1/2 small red onion, thinly sliced",
      "1 lemon, cut into wedges",
      "2 teaspoons extra virgin olive oil",
      "Salt and freshly ground black pepper to taste",
      "Red pepper flakes (optional)",
      "Fresh dill or chives for garnish",
    ],
    instructions: [
      "Toast the bread slices until golden and crisp.",
      "Cut the avocado in half, remove the pit, and scoop the flesh into a bowl. Mash with a fork and season with salt, pepper, and a squeeze of lemon juice.",
      "Spread the mashed avocado evenly over the toast slices.",
      "Layer the smoked salmon on top of the avocado.",
      "Scatter the capers and red onion slices over the salmon.",
      "Drizzle with olive oil and add another squeeze of lemon juice.",
      "Sprinkle with red pepper flakes if desired and garnish with fresh dill or chives.",
      "Serve immediately with extra lemon wedges on the side.",
    ],
  },
  {
    id: 2,
    title: "Greek Yogurt Parfait with Honey and Berries",
    description:
      "Layers of creamy Greek yogurt, fresh berries, honey, and crunchy granola create a balanced breakfast that's both satisfying and nutritious.",
    image: "/greek-yogurt-parfait.png",
    heroImage: "/greek-yogurt-parfait.png",
    time: "10 mins",
    prepTime: "10 mins",
    cookTime: "0 mins",
    difficulty: "Easy",
    servings: 2,
    tags: ["Breakfast", "Pescatarian", "Vegetarian", "No-Cook", "Healthy"],
    ingredients: [
      "2 cups Greek yogurt",
      "1 cup mixed berries (strawberries, blueberries, raspberries)",
      "4 tablespoons honey",
      "1 cup granola",
      "2 tablespoons chia seeds",
      "2 tablespoons sliced almonds",
      "Fresh mint leaves for garnish (optional)",
    ],
    instructions: [
      "In two serving glasses or bowls, begin layering with 1/4 cup of Greek yogurt in each.",
      "Add a layer of mixed berries on top of the yogurt.",
      "Drizzle 1 tablespoon of honey over the berries in each glass.",
      "Add a layer of granola (about 1/4 cup per glass).",
      "Repeat the layers, ending with a final layer of yogurt on top.",
      "Garnish with remaining berries, a drizzle of honey, chia seeds, and sliced almonds.",
      "Add a sprig of fresh mint if desired.",
      "Serve immediately or refrigerate for up to 2 hours (add granola just before serving to maintain crunch).",
    ],
  },
  {
    id: 3,
    title: "Spinach and Feta Omelette",
    description:
      "A fluffy omelette filled with sautéed spinach, crumbled feta, and herbs. This protein-rich breakfast will keep you energized all morning.",
    image: "/spinach-feta-omelette.png",
    heroImage: "/placeholder.svg?key=dvcex",
    time: "15 mins",
    prepTime: "5 mins",
    cookTime: "10 mins",
    difficulty: "Medium",
    servings: 2,
    tags: ["Breakfast", "Pescatarian", "Vegetarian", "High-Protein", "Gluten-Free"],
    ingredients: [
      "6 large eggs",
      "2 tablespoons milk or water",
      "2 cups fresh spinach, roughly chopped",
      "1/2 cup crumbled feta cheese",
      "2 tablespoons olive oil",
      "1 small onion, finely diced",
      "1 clove garlic, minced",
      "1 tablespoon fresh dill, chopped (or 1 teaspoon dried)",
      "Salt and freshly ground black pepper to taste",
      "Cherry tomatoes and extra feta for garnish",
    ],
    instructions: [
      "In a bowl, whisk together eggs and milk until well combined. Season with salt and pepper.",
      "Heat 1 tablespoon of olive oil in a non-stick skillet over medium heat. Add onion and sauté until translucent, about 3 minutes.",
      "Add garlic and cook for another 30 seconds until fragrant.",
      "Add spinach and cook until wilted, about 1-2 minutes. Remove the vegetable mixture from the pan and set aside.",
      "Wipe the skillet clean and heat the remaining tablespoon of olive oil over medium heat.",
      "Pour half the egg mixture into the skillet, tilting the pan to ensure the eggs cover the entire surface.",
      "When the eggs begin to set (about 2 minutes), sprinkle half of the spinach mixture and half of the feta cheese over one half of the omelette.",
      "Sprinkle with half of the dill. Carefully fold the other half of the omelette over the filling.",
      "Cook for another minute, then slide onto a plate. Repeat with the remaining ingredients to make the second omelette.",
      "Garnish with cherry tomatoes and additional feta cheese if desired.",
    ],
  },
  {
    id: 4,
    title: "Blueberry Lemon Pancakes",
    description:
      "Fluffy pancakes studded with fresh blueberries and brightened with lemon zest. Topped with maple syrup and more berries for a delightful breakfast treat.",
    image: "/blueberry-lemon-pancakes.png",
    heroImage: "/blueberry-lemon-pancakes.png",
    time: "25 mins",
    prepTime: "10 mins",
    cookTime: "15 mins",
    difficulty: "Medium",
    servings: 4,
    tags: ["Breakfast", "Pescatarian", "Vegetarian", "Sweet"],
    ingredients: [
      "1 1/2 cups all-purpose flour",
      "2 tablespoons sugar",
      "1 tablespoon baking powder",
      "1/2 teaspoon salt",
      "1 1/4 cups milk",
      "2 large eggs",
      "3 tablespoons unsalted butter, melted and cooled",
      "1 teaspoon vanilla extract",
      "Zest of 1 lemon",
      "1 cup fresh blueberries, plus more for serving",
      "Vegetable oil or butter for cooking",
      "Maple syrup for serving",
      "Powdered sugar for dusting (optional)",
    ],
    instructions: [
      "In a large bowl, whisk together flour, sugar, baking powder, and salt.",
      "In another bowl, whisk together milk, eggs, melted butter, vanilla extract, and lemon zest.",
      "Pour the wet ingredients into the dry ingredients and stir just until combined (the batter should be slightly lumpy).",
      "Gently fold in the blueberries.",
      "Heat a griddle or large non-stick skillet over medium heat. Lightly grease with oil or butter.",
      "For each pancake, pour about 1/4 cup of batter onto the griddle. Cook until bubbles form on the surface and the edges look set, about 2-3 minutes.",
      "Flip the pancakes and cook until golden brown on the other side, about 1-2 minutes more.",
      "Transfer to a plate and keep warm while cooking the remaining pancakes.",
      "Serve warm, topped with additional blueberries, maple syrup, and a dusting of powdered sugar if desired.",
    ],
  },
  {
    id: 5,
    title: "Mediterranean Breakfast Bowl",
    description:
      "A savory breakfast bowl with quinoa, roasted vegetables, soft-boiled eggs, and Mediterranean flavors. Nutritious, filling, and perfect for a slow weekend morning.",
    image: "/mediterranean-breakfast-bowl.png",
    heroImage: "/mediterranean-breakfast-bowl.png",
    time: "30 mins",
    prepTime: "10 mins",
    cookTime: "20 mins",
    difficulty: "Medium",
    servings: 2,
    tags: ["Breakfast", "Pescatarian", "Vegetarian", "Mediterranean", "Healthy"],
    ingredients: [
      "1 cup cooked quinoa",
      "2 large eggs",
      "1 cup cherry tomatoes, halved",
      "1 cucumber, diced",
      "1/2 red onion, thinly sliced",
      "1/4 cup Kalamata olives, pitted and halved",
      "1/4 cup crumbled feta cheese",
      "1 tablespoon olive oil",
      "1 tablespoon lemon juice",
      "1 teaspoon dried oregano",
      "Salt and freshly ground black pepper to taste",
      "Fresh parsley, chopped, for garnish",
      "2 tablespoons tzatziki sauce (optional)",
    ],
    instructions: [
      "Bring a small pot of water to a boil. Carefully add the eggs and cook for 6-7 minutes for soft-boiled eggs.",
      "Transfer the eggs to an ice bath to stop the cooking process. Once cooled, peel and halve the eggs.",
      "In a small bowl, whisk together olive oil, lemon juice, dried oregano, salt, and pepper to make the dressing.",
      "Divide the cooked quinoa between two bowls.",
      "Arrange the cherry tomatoes, cucumber, red onion, and Kalamata olives on top of the quinoa.",
      "Place the halved soft-boiled eggs on top.",
      "Sprinkle with crumbled feta cheese.",
      "Drizzle the dressing over the bowls.",
      "Garnish with chopped fresh parsley and a dollop of tzatziki sauce if using.",
      "Serve immediately.",
    ],
  },

  // LUNCH RECIPES (5)
  {
    id: 6,
    title: "Tuna Niçoise Salad",
    description:
      "A classic French salad featuring seared tuna, tender potatoes, crisp green beans, and hard-boiled eggs, all dressed in a tangy Dijon vinaigrette.",
    image: "/tuna-nicoise-salad.png",
    heroImage: "/tuna-nicoise-salad.png",
    time: "35 mins",
    prepTime: "20 mins",
    cookTime: "15 mins",
    difficulty: "Medium",
    servings: 2,
    tags: ["Lunch", "Pescatarian", "French", "Salad", "Healthy"],
    ingredients: [
      "8 oz fresh tuna steak",
      "8 small new potatoes, halved",
      "6 oz green beans, trimmed",
      "2 large eggs",
      "1 cup cherry tomatoes, halved",
      "1/4 cup Niçoise or Kalamata olives",
      "2 cups mixed salad greens",
      "1 small shallot, finely chopped",
      "2 tablespoons fresh lemon juice",
      "1 tablespoon Dijon mustard",
      "3 tablespoons extra virgin olive oil",
      "1 teaspoon fresh thyme leaves",
      "Salt and freshly ground black pepper to taste",
      "Fresh parsley, chopped, for garnish",
    ],
    instructions: [
      "Place the potatoes in a pot of salted water and bring to a boil. Cook until tender, about 10-12 minutes. Drain and let cool.",
      "In another pot, boil the eggs for 8 minutes for hard-boiled eggs. Transfer to an ice bath, then peel and quarter them.",
      "Blanch the green beans in boiling water for 3-4 minutes until crisp-tender. Transfer to an ice bath to stop the cooking, then drain.",
      "Season the tuna steak with salt and pepper. Heat 1 tablespoon of olive oil in a skillet over high heat. Sear the tuna for 1-2 minutes per side for rare, or longer if preferred. Let rest, then slice.",
      "In a small bowl, whisk together shallot, lemon juice, Dijon mustard, remaining olive oil, thyme, salt, and pepper to make the dressing.",
      "Arrange the mixed salad greens on two plates. Top with potatoes, green beans, tomatoes, olives, and egg quarters.",
      "Place the seared tuna slices on top.",
      "Drizzle with the dressing and garnish with fresh parsley.",
      "Serve immediately.",
    ],
  },
  {
    id: 7,
    title: "Mediterranean Chickpea Salad",
    description:
      "A protein-packed vegetarian salad with chickpeas, fresh vegetables, feta cheese, and a zesty lemon herb dressing. Perfect for meal prep or a light lunch.",
    image: "/mediterranean-chickpea-salad.png",
    heroImage: "/placeholder.svg?key=harra",
    time: "20 mins",
    prepTime: "20 mins",
    cookTime: "0 mins",
    difficulty: "Easy",
    servings: 4,
    tags: ["Lunch", "Pescatarian", "Vegetarian", "Mediterranean", "Salad", "No-Cook"],
    ingredients: [
      "2 cans (15 oz each) chickpeas, drained and rinsed",
      "1 English cucumber, diced",
      "1 pint cherry tomatoes, halved",
      "1 red bell pepper, diced",
      "1/2 red onion, finely chopped",
      "1/2 cup Kalamata olives, pitted and halved",
      "1/2 cup crumbled feta cheese",
      "1/4 cup fresh parsley, chopped",
      "1/4 cup fresh mint, chopped",
      "3 tablespoons extra virgin olive oil",
      "2 tablespoons fresh lemon juice",
      "1 tablespoon red wine vinegar",
      "1 clove garlic, minced",
      "1 teaspoon dried oregano",
      "Salt and freshly ground black pepper to taste",
    ],
    instructions: [
      "In a large bowl, combine chickpeas, cucumber, cherry tomatoes, red bell pepper, red onion, Kalamata olives, feta cheese, parsley, and mint.",
      "In a small bowl, whisk together olive oil, lemon juice, red wine vinegar, garlic, oregano, salt, and pepper to make the dressing.",
      "Pour the dressing over the salad and toss gently to combine.",
      "Taste and adjust seasoning if needed.",
      "For best flavor, refrigerate for at least 30 minutes before serving to allow the flavors to meld.",
      "Serve chilled or at room temperature.",
    ],
  },
  {
    id: 8,
    title: "Shrimp and Avocado Wrap",
    description:
      "Tender sautéed shrimp, creamy avocado, and crisp vegetables wrapped in a soft tortilla with a zesty lime dressing. A quick and satisfying lunch option.",
    image: "/shrimp-avocado-wrap.png",
    heroImage: "/shrimp-avocado-wrap.png",
    time: "20 mins",
    prepTime: "10 mins",
    cookTime: "10 mins",
    difficulty: "Easy",
    servings: 2,
    tags: ["Lunch", "Pescatarian", "Seafood", "Quick", "Wrap"],
    ingredients: [
      "12 large shrimp, peeled and deveined",
      "2 large flour tortillas or wraps",
      "1 ripe avocado, sliced",
      "1 cup lettuce or mixed greens",
      "1/2 cup cherry tomatoes, halved",
      "1/4 red onion, thinly sliced",
      "1/4 cup cilantro leaves",
      "1 tablespoon olive oil",
      "1 teaspoon cajun seasoning or taco seasoning",
      "1 lime, juiced and zested",
      "2 tablespoons Greek yogurt",
      "1 tablespoon mayonnaise",
      "1 clove garlic, minced",
      "Salt and freshly ground black pepper to taste",
      "Hot sauce to taste (optional)",
    ],
    instructions: [
      "In a bowl, toss the shrimp with olive oil, cajun or taco seasoning, salt, and pepper.",
      "Heat a skillet over medium-high heat. Add the shrimp and cook for 2-3 minutes per side until pink and opaque. Remove from heat and set aside.",
      "In a small bowl, mix together Greek yogurt, mayonnaise, lime juice, lime zest, garlic, salt, and pepper to make the dressing.",
      "Warm the tortillas slightly to make them more pliable.",
      "Spread a thin layer of the dressing on each tortilla.",
      "Layer the lettuce or mixed greens, avocado slices, cherry tomatoes, red onion, and cilantro leaves on each tortilla.",
      "Add the cooked shrimp on top.",
      "Drizzle with additional dressing and hot sauce if desired.",
      "Fold in the sides of the tortilla and roll up tightly to form a wrap.",
      "Cut in half diagonally and serve immediately.",
    ],
  },
  {
    id: 9,
    title: "Caprese Panini with Pesto",
    description:
      "A warm, pressed sandwich with fresh mozzarella, juicy tomatoes, basil pesto, and balsamic glaze. This Italian-inspired panini is perfect for a quick lunch.",
    image: "/placeholder.svg?height=400&width=600&query=caprese panini with pesto",
    heroImage: "/placeholder.svg?height=800&width=1200&query=caprese panini with mozzarella and tomato",
    time: "15 mins",
    prepTime: "5 mins",
    cookTime: "10 mins",
    difficulty: "Easy",
    servings: 2,
    tags: ["Lunch", "Pescatarian", "Vegetarian", "Italian", "Sandwich"],
    ingredients: [
      "4 slices sourdough bread or ciabatta",
      "8 oz fresh mozzarella cheese, sliced",
      "2 large tomatoes, sliced",
      "1/4 cup basil pesto",
      "2 tablespoons balsamic glaze",
      "2 tablespoons olive oil",
      "Fresh basil leaves",
      "Salt and freshly ground black pepper to taste",
    ],
    instructions: [
      "Brush the outside of each bread slice with olive oil.",
      "Spread basil pesto on the inside of each bread slice.",
      "Layer mozzarella slices and tomato slices on two of the bread slices.",
      "Season with salt and pepper, and add fresh basil leaves.",
      "Drizzle with balsamic glaze.",
      "Top with the remaining bread slices, pesto side down.",
      "Heat a panini press or a skillet over medium heat.",
      "If using a panini press, cook the sandwiches until the bread is golden and the cheese is melted, about 3-5 minutes.",
      "If using a skillet, place the sandwiches in the pan and press down with a heavy pot or pan. Cook for 2-3 minutes per side until golden and crispy, and the cheese is melted.",
      "Cut in half and serve warm.",
    ],
  },
  {
    id: 10,
    title: "Lentil and Roasted Vegetable Bowl",
    description:
      "A hearty bowl of protein-rich lentils topped with roasted vegetables, crumbled feta, and a tahini dressing. A nutritious and satisfying vegetarian lunch option.",
    image: "/placeholder.svg?height=400&width=600&query=lentil and roasted vegetable bowl",
    heroImage: "/placeholder.svg?height=800&width=1200&query=lentil bowl with roasted vegetables and tahini",
    time: "40 mins",
    prepTime: "15 mins",
    cookTime: "25 mins",
    difficulty: "Medium",
    servings: 4,
    tags: ["Lunch", "Pescatarian", "Vegetarian", "Bowl", "Healthy"],
    ingredients: [
      "1 cup green or brown lentils, rinsed",
      "2 cups vegetable broth",
      "1 bay leaf",
      "1 sweet potato, diced",
      "1 red bell pepper, diced",
      "1 zucchini, diced",
      "1 red onion, cut into wedges",
      "2 tablespoons olive oil",
      "1 teaspoon ground cumin",
      "1 teaspoon smoked paprika",
      "1/2 cup crumbled feta cheese",
      "1/4 cup fresh parsley, chopped",
      "3 tablespoons tahini",
      "2 tablespoons lemon juice",
      "1 clove garlic, minced",
      "3-4 tablespoons water",
      "Salt and freshly ground black pepper to taste",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "In a medium saucepan, combine lentils, vegetable broth, and bay leaf. Bring to a boil, then reduce heat and simmer, covered, for 20-25 minutes until lentils are tender but not mushy. Drain any excess liquid and discard the bay leaf.",
      "Meanwhile, on a large baking sheet, toss sweet potato, red bell pepper, zucchini, and red onion with olive oil, cumin, smoked paprika, salt, and pepper.",
      "Roast vegetables for 20-25 minutes, stirring halfway through, until tender and slightly caramelized.",
      "While everything is cooking, make the tahini dressing: In a small bowl, whisk together tahini, lemon juice, garlic, water, salt, and pepper until smooth and pourable. Add more water if needed to reach desired consistency.",
      "To assemble the bowls, divide the cooked lentils among four bowls. Top with roasted vegetables and crumbled feta cheese.",
      "Drizzle with tahini dressing and garnish with chopped parsley.",
      "Serve warm or at room temperature.",
    ],
  },

  // DINNER RECIPES (5)
  {
    id: 11,
    title: "Herb-Crusted Salmon with Roasted Vegetables",
    description:
      "Tender salmon fillets coated in a flavorful herb crust, served with colorful roasted vegetables. A nutritious and elegant dinner option that's surprisingly easy to prepare.",
    image: "/placeholder.svg?height=400&width=600&query=herb crusted salmon with vegetables",
    heroImage: "/placeholder.svg?height=800&width=1200&query=herb crusted salmon fillet with roasted vegetables",
    time: "35 mins",
    prepTime: "15 mins",
    cookTime: "20 mins",
    difficulty: "Medium",
    servings: 4,
    tags: ["Dinner", "Pescatarian", "Seafood", "Healthy", "Gluten-Free"],
    ingredients: [
      "4 salmon fillets (6 oz each)",
      "2 tablespoons Dijon mustard",
      "2 tablespoons olive oil, divided",
      "1/4 cup fresh parsley, finely chopped",
      "2 tablespoons fresh dill, finely chopped",
      "2 tablespoons fresh chives, finely chopped",
      "1 lemon, zested and cut into wedges",
      "1 zucchini, sliced",
      "1 yellow squash, sliced",
      "1 red bell pepper, sliced",
      "1 red onion, cut into wedges",
      "2 cups cherry tomatoes",
      "3 cloves garlic, minced",
      "1 teaspoon dried oregano",
      "Salt and freshly ground black pepper to taste",
    ],
    instructions: [
      "Preheat oven to 425°F (220°C).",
      "On a large baking sheet, toss zucchini, yellow squash, bell pepper, red onion, cherry tomatoes, and garlic with 1 tablespoon olive oil, dried oregano, salt, and pepper.",
      "Spread vegetables in a single layer and roast for 10 minutes.",
      "Meanwhile, in a small bowl, mix together parsley, dill, chives, lemon zest, salt, and pepper to create the herb crust.",
      "Pat the salmon fillets dry with paper towels. Brush each fillet with Dijon mustard and drizzle with the remaining olive oil.",
      "Press the herb mixture onto the top of each salmon fillet.",
      "Remove the baking sheet from the oven and push the vegetables to the sides to make room for the salmon in the center.",
      "Place the salmon fillets on the baking sheet and return to the oven.",
      "Roast for an additional 10-12 minutes, or until the salmon is cooked through and flakes easily with a fork.",
      "Serve the salmon with the roasted vegetables and lemon wedges on the side.",
    ],
  },
  {
    id: 12,
    title: "Shrimp and Vegetable Stir-Fry with Garlic Sauce",
    description:
      "Succulent shrimp and crisp vegetables quickly stir-fried in a flavorful garlic sauce. Served over rice or noodles for a satisfying weeknight dinner that's ready in minutes.",
    image: "/placeholder.svg?height=400&width=600&query=shrimp and vegetable stir fry",
    heroImage: "/placeholder.svg?height=800&width=1200&query=shrimp stir fry with vegetables in wok",
    time: "25 mins",
    prepTime: "15 mins",
    cookTime: "10 mins",
    difficulty: "Medium",
    servings: 4,
    tags: ["Dinner", "Pescatarian", "Seafood", "Asian", "Quick"],
    ingredients: [
      "1 lb large shrimp, peeled and deveined",
      "2 tablespoons vegetable oil, divided",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "2 cups broccoli florets",
      "1 carrot, julienned",
      "1 cup snap peas",
      "3 cloves garlic, minced",
      "1 tablespoon ginger, grated",
      "3 tablespoons soy sauce",
      "1 tablespoon oyster sauce",
      "1 tablespoon rice vinegar",
      "1 teaspoon sesame oil",
      "1 teaspoon brown sugar",
      "1/2 teaspoon red pepper flakes (optional)",
      "2 green onions, sliced",
      "1 tablespoon sesame seeds",
      "Cooked rice or noodles, for serving",
    ],
    instructions: [
      "In a small bowl, whisk together soy sauce, oyster sauce, rice vinegar, sesame oil, brown sugar, and red pepper flakes (if using) to make the sauce.",
      "Heat 1 tablespoon of vegetable oil in a large wok or skillet over high heat. Add shrimp and cook for 1-2 minutes per side until pink and opaque. Remove from the wok and set aside.",
      "Add the remaining tablespoon of oil to the wok. Add garlic and ginger and stir-fry for 30 seconds until fragrant.",
      "Add broccoli and carrots and stir-fry for 2 minutes.",
      "Add bell peppers and snap peas and continue to stir-fry for another 2-3 minutes until vegetables are crisp-tender.",
      "Return the shrimp to the wok and pour the sauce over everything.",
      "Toss to coat and cook for another 1-2 minutes until the sauce thickens slightly and everything is well combined.",
      "Garnish with sliced green onions and sesame seeds.",
      "Serve hot over cooked rice or noodles.",
    ],
  },
  {
    id: 13,
    title: "Eggplant Parmesan",
    description:
      "Layers of breaded eggplant, marinara sauce, and melted cheese baked to perfection. This classic Italian vegetarian dish is hearty, comforting, and full of flavor.",
    image: "/placeholder.svg?height=400&width=600&query=eggplant parmesan",
    heroImage: "/placeholder.svg?height=800&width=1200&query=baked eggplant parmesan with cheese",
    time: "60 mins",
    prepTime: "30 mins",
    cookTime: "30 mins",
    difficulty: "Medium",
    servings: 6,
    tags: ["Dinner", "Pescatarian", "Vegetarian", "Italian", "Baked"],
    ingredients: [
      "2 large eggplants, sliced into 1/4-inch rounds",
      "2 cups Italian-seasoned breadcrumbs",
      "1/2 cup grated Parmesan cheese, plus more for layering",
      "3 large eggs, beaten",
      "1/4 cup milk",
      "1/2 cup all-purpose flour",
      "1/4 cup olive oil",
      "3 cups marinara sauce",
      "16 oz fresh mozzarella cheese, sliced",
      "1/4 cup fresh basil leaves, torn",
      "1 teaspoon dried oregano",
      "Salt and freshly ground black pepper to taste",
    ],
    instructions: [
      "Preheat oven to 375°F (190°C).",
      "Sprinkle eggplant slices with salt and place in a colander. Let sit for 20 minutes to draw out moisture, then pat dry with paper towels.",
      "Set up a breading station: Place flour in one shallow dish, beaten eggs mixed with milk in a second dish, and breadcrumbs mixed with 1/2 cup Parmesan cheese in a third dish.",
      "Dredge each eggplant slice in flour, then dip in egg mixture, and finally coat with breadcrumb mixture, pressing gently to adhere.",
      "Heat olive oil in a large skillet over medium heat. Working in batches, cook eggplant slices until golden brown, about 2-3 minutes per side. Transfer to a paper towel-lined plate.",
      "Spread 1/2 cup marinara sauce in the bottom of a 9x13-inch baking dish.",
      "Arrange a layer of eggplant slices over the sauce, slightly overlapping. Top with 1 cup marinara sauce, one-third of the mozzarella, and a sprinkle of Parmesan and torn basil.",
      "Repeat layers twice more, ending with cheese on top. Sprinkle with dried oregano.",
      "Cover with foil and bake for 20 minutes. Remove foil and bake for an additional 10 minutes until cheese is bubbly and golden.",
      "Let rest for 10 minutes before serving to allow the layers to set.",
    ],
  },
  {
    id: 14,
    title: "Mushroom Risotto",
    description:
      "Creamy Arborio rice slowly cooked with mushrooms, white wine, and Parmesan cheese. This classic Italian dish is elegant, comforting, and perfect for a special dinner.",
    image: "/placeholder.svg?height=400&width=600&query=mushroom risotto",
    heroImage: "/placeholder.svg?height=800&width=1200&query=creamy mushroom risotto in bowl",
    time: "45 mins",
    prepTime: "15 mins",
    cookTime: "30 mins",
    difficulty: "Medium",
    servings: 4,
    tags: ["Dinner", "Pescatarian", "Vegetarian", "Italian", "Creamy"],
    ingredients: [
      "1 1/2 cups Arborio rice",
      "6 cups vegetable broth, kept warm",
      "1 lb mixed mushrooms (cremini, shiitake, oyster), sliced",
      "1 small onion, finely diced",
      "3 cloves garlic, minced",
      "1/2 cup dry white wine",
      "3 tablespoons butter, divided",
      "2 tablespoons olive oil",
      "1/2 cup grated Parmesan cheese, plus more for serving",
      "2 tablespoons fresh thyme leaves",
      "2 tablespoons fresh parsley, chopped",
      "Salt and freshly ground black pepper to taste",
      "Truffle oil for drizzling (optional)",
    ],
    instructions: [
      "In a large pot or Dutch oven, heat 1 tablespoon butter and olive oil over medium heat. Add mushrooms and cook until golden brown and their liquid has evaporated, about 8-10 minutes. Season with salt and pepper, then transfer to a plate.",
      "In the same pot, add another tablespoon of butter. Add onion and cook until translucent, about 3-4 minutes. Add garlic and cook for another 30 seconds until fragrant.",
      "Add Arborio rice and stir to coat with butter and oil. Toast the rice for 1-2 minutes until the edges become translucent.",
      "Pour in the white wine and stir until absorbed.",
      "Begin adding the warm broth, one ladle at a time, stirring frequently. Wait until each addition is almost fully absorbed before adding more.",
      "Continue this process for about 18-20 minutes, until the rice is creamy and al dente (tender but with a slight bite).",
      "Stir in the cooked mushrooms, remaining tablespoon of butter, Parmesan cheese, and thyme leaves.",
      "Remove from heat and let rest for 2 minutes. The risotto should be creamy and slightly loose (it will thicken as it sits).",
      "Serve immediately, garnished with chopped parsley, additional Parmesan cheese, and a drizzle of truffle oil if desired.",
    ],
  },
  {
    id: 15,
    title: "Grilled Fish Tacos with Avocado Crema",
    description:
      "Flaky grilled fish topped with crunchy slaw and creamy avocado sauce, all wrapped in warm tortillas. These fresh and flavorful tacos are perfect for a casual dinner.",
    image: "/placeholder.svg?height=400&width=600&query=fish tacos with avocado",
    heroImage: "/placeholder.svg?height=800&width=1200&query=grilled fish tacos with slaw and avocado",
    time: "30 mins",
    prepTime: "15 mins",
    cookTime: "15 mins",
    difficulty: "Medium",
    servings: 4,
    tags: ["Dinner", "Pescatarian", "Seafood", "Mexican", "Grilled"],
    ingredients: [
      "1 1/2 lbs firm white fish (such as cod, mahi-mahi, or tilapia)",
      "8 small corn or flour tortillas",
      "2 tablespoons olive oil",
      "1 tablespoon lime juice",
      "1 teaspoon ground cumin",
      "1 teaspoon chili powder",
      "1/2 teaspoon garlic powder",
      "1/4 teaspoon cayenne pepper (optional)",
      "For the slaw:",
      "2 cups shredded cabbage",
      "1/2 cup grated carrot",
      "1/4 cup red onion, thinly sliced",
      "2 tablespoons cilantro, chopped",
      "1 tablespoon lime juice",
      "1 tablespoon olive oil",
      "For the avocado crema:",
      "1 ripe avocado",
      "1/4 cup sour cream or Greek yogurt",
      "2 tablespoons lime juice",
      "1 clove garlic, minced",
      "Salt and freshly ground black pepper to taste",
      "Lime wedges and hot sauce for serving",
    ],
    instructions: [
      "In a small bowl, mix together olive oil, lime juice, cumin, chili powder, garlic powder, cayenne (if using), salt, and pepper. Rub this mixture all over the fish.",
      "For the slaw, combine cabbage, carrot, red onion, and cilantro in a bowl. Toss with lime juice, olive oil, salt, and pepper. Set aside.",
      "For the avocado crema, blend avocado, sour cream or yogurt, lime juice, garlic, salt, and pepper until smooth. If too thick, add a tablespoon of water to reach desired consistency.",
      "Preheat grill or grill pan to medium-high heat. Grill fish for 3-4 minutes per side, or until it flakes easily with a fork.",
      "While the fish is cooking, warm the tortillas on the grill or in a dry skillet for about 30 seconds per side.",
      "Break the grilled fish into chunks.",
      "To assemble tacos, place fish pieces on warm tortillas, top with slaw and a dollop of avocado crema.",
      "Serve with lime wedges and hot sauce on the side.",
    ],
  },

  // SNACK RECIPES (5)
  {
    id: 16,
    title: "Spiced Roasted Chickpeas",
    description:
      "Crispy, crunchy chickpeas roasted with a blend of spices. These protein-packed snacks are perfect for munching on the go or as a healthy alternative to chips.",
    image: "/placeholder.svg?height=400&width=600&query=spiced roasted chickpeas",
    heroImage: "/placeholder.svg?height=800&width=1200&query=crispy roasted chickpeas with spices in bowl",
    time: "40 mins",
    prepTime: "10 mins",
    cookTime: "30 mins",
    difficulty: "Easy",
    servings: 4,
    tags: ["Snack", "Pescatarian", "Vegetarian", "Healthy", "Gluten-Free"],
    ingredients: [
      "2 cans (15 oz each) chickpeas, drained and rinsed",
      "2 tablespoons olive oil",
      "1 teaspoon ground cumin",
      "1 teaspoon smoked paprika",
      "1/2 teaspoon garlic powder",
      "1/2 teaspoon onion powder",
      "1/4 teaspoon cayenne pepper (optional)",
      "1 teaspoon salt",
      "1/2 teaspoon black pepper",
      "Fresh parsley, finely chopped (optional)",
    ],
    instructions: [
      "Preheat oven to 400°F (200°C) and line a baking sheet with parchment paper.",
      "After draining and rinsing the chickpeas, spread them on a clean kitchen towel or paper towels and pat dry. Remove any loose skins for extra crispiness.",
      "In a large bowl, toss the dried chickpeas with olive oil until well coated.",
      "In a small bowl, mix together cumin, smoked paprika, garlic powder, onion powder, cayenne pepper (if using), salt, and black pepper.",
      "Sprinkle the spice mixture over the chickpeas and toss to coat evenly.",
      "Spread the chickpeas in a single layer on the prepared baking sheet.",
      "Roast for 25-30 minutes, shaking the pan halfway through, until the chickpeas are golden brown and crispy.",
      "Let cool for 5-10 minutes before serving (they'll get crispier as they cool).",
      "If desired, sprinkle with fresh parsley before serving.",
      "Store in an airtight container at room temperature for up to 3 days.",
    ],
  },
  {
    id: 17,
    title: "Greek Yogurt Tzatziki Dip with Vegetables",
    description:
      "Creamy Greek yogurt dip with cucumber, garlic, and herbs, served with fresh vegetable sticks. A refreshing and protein-rich snack that's perfect for afternoon cravings.",
    image: "/placeholder.svg?height=400&width=600&query=tzatziki dip with vegetables",
    heroImage: "/placeholder.svg?height=800&width=1200&query=greek yogurt tzatziki dip with fresh vegetable sticks",
    time: "15 mins",
    prepTime: "15 mins",
    cookTime: "0 mins",
    difficulty: "Easy",
    servings: 4,
    tags: ["Snack", "Pescatarian", "Vegetarian", "Greek", "No-Cook", "Healthy"],
    ingredients: [
      "2 cups Greek yogurt",
      "1 English cucumber, grated",
      "2 cloves garlic, minced",
      "2 tablespoons extra virgin olive oil",
      "1 tablespoon fresh lemon juice",
      "2 tablespoons fresh dill, chopped",
      "1 tablespoon fresh mint, chopped (optional)",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "For serving:",
      "Carrot sticks",
      "Cucumber slices",
      "Bell pepper strips",
      "Cherry tomatoes",
      "Celery sticks",
      "Broccoli florets",
    ],
    instructions: [
      "Grate the cucumber and place it in a clean kitchen towel or cheesecloth. Squeeze out as much liquid as possible.",
      "In a medium bowl, combine Greek yogurt, drained grated cucumber, minced garlic, olive oil, lemon juice, dill, mint (if using), salt, and pepper.",
      "Stir well to combine all ingredients. Taste and adjust seasoning if needed.",
      "Cover and refrigerate for at least 30 minutes to allow flavors to meld (longer is better).",
      "Serve chilled with an assortment of fresh vegetable sticks and slices.",
      "Store any leftover tzatziki in an airtight container in the refrigerator for up to 3 days.",
    ],
  },
  {
    id: 18,
    title: "Caprese Skewers",
    description:
      "Bite-sized skewers with cherry tomatoes, fresh mozzarella, and basil drizzled with balsamic glaze. These no-cook appetizers are perfect for entertaining or a quick snack.",
    image: "/placeholder.svg?height=400&width=600&query=caprese skewers",
    heroImage: "/placeholder.svg?height=800&width=1200&query=caprese skewers with balsamic glaze on platter",
    time: "15 mins",
    prepTime: "15 mins",
    cookTime: "0 mins",
    difficulty: "Easy",
    servings: 4,
    tags: ["Snack", "Pescatarian", "Vegetarian", "Italian", "No-Cook", "Appetizer"],
    ingredients: [
      "24 cherry tomatoes",
      "12 oz fresh mozzarella pearls (or larger mozzarella cut into cubes)",
      "24 fresh basil leaves",
      "1/4 cup balsamic glaze",
      "2 tablespoons extra virgin olive oil",
      "Sea salt and freshly ground black pepper to taste",
      "24 small wooden skewers or toothpicks",
    ],
    instructions: [
      "If using larger mozzarella, cut it into bite-sized cubes similar in size to the cherry tomatoes.",
      "Thread a cherry tomato, a basil leaf (folded if large), and a mozzarella pearl onto each skewer or toothpick.",
      "Arrange the skewers on a serving platter.",
      "Drizzle with balsamic glaze and olive oil.",
      "Sprinkle with sea salt and freshly ground black pepper.",
      "Serve immediately or refrigerate for up to 2 hours before serving.",
    ],
  },
  {
    id: 19,
    title: "Avocado Toast with Smoked Salmon",
    description:
      "Creamy avocado spread on toasted bread, topped with smoked salmon and fresh herbs. A satisfying snack that's packed with healthy fats and protein.",
    image: "/placeholder.svg?height=400&width=600&query=avocado toast with salmon",
    heroImage: "/placeholder.svg?height=800&width=1200&query=avocado toast with smoked salmon and herbs",
    time: "10 mins",
    prepTime: "10 mins",
    cookTime: "0 mins",
    difficulty: "Easy",
    servings: 2,
    tags: ["Snack", "Pescatarian", "Seafood", "Quick", "Healthy"],
    ingredients: [
      "2 slices whole grain bread",
      "1 ripe avocado",
      "2 oz smoked salmon",
      "1 tablespoon fresh lemon juice",
      "1 tablespoon extra virgin olive oil",
      "1 tablespoon fresh dill, chopped",
      "1 tablespoon capers, drained",
      "1/4 red onion, thinly sliced",
      "Red pepper flakes (optional)",
      "Salt and freshly ground black pepper to taste",
    ],
    instructions: [
      "Toast the bread slices until golden and crisp.",
      "In a small bowl, mash the avocado with lemon juice, salt, and pepper.",
      "Spread the mashed avocado evenly over the toast slices.",
      "Top each slice with smoked salmon.",
      "Sprinkle with red onion slices, capers, and fresh dill.",
      "Drizzle with olive oil and add red pepper flakes if desired.",
      "Season with additional salt and pepper to taste.",
      "Serve immediately.",
    ],
  },
  {
    id: 20,
    title: "Stuffed Dates with Goat Cheese and Walnuts",
    description:
      "Sweet Medjool dates stuffed with creamy goat cheese and crunchy walnuts, drizzled with honey. These bite-sized treats are the perfect balance of sweet and savory.",
    image: "/placeholder.svg?height=400&width=600&query=stuffed dates with goat cheese",
    heroImage: "/placeholder.svg?height=800&width=1200&query=stuffed dates with goat cheese walnuts and honey",
    time: "15 mins",
    prepTime: "15 mins",
    cookTime: "0 mins",
    difficulty: "Easy",
    servings: 4,
    tags: ["Snack", "Pescatarian", "Vegetarian", "No-Cook", "Sweet and Savory"],
    ingredients: [
      "16 Medjool dates",
      "4 oz goat cheese, softened",
      "1/4 cup walnuts, chopped and lightly toasted",
      "2 tablespoons honey",
      "1 teaspoon orange zest (optional)",
      "1/4 teaspoon cinnamon (optional)",
      "Pinch of sea salt",
    ],
    instructions: [
      "Make a lengthwise slit in each date and remove the pit.",
      "In a small bowl, mix the goat cheese with orange zest and cinnamon if using.",
      "Stuff each date with about 1 teaspoon of the goat cheese mixture.",
      "Press a few pieces of chopped walnuts into the goat cheese filling of each date.",
      "Arrange the stuffed dates on a serving plate.",
      "Drizzle with honey and sprinkle with a pinch of sea salt.",
      "Serve at room temperature.",
      "These can be prepared up to 24 hours in advance and stored in the refrigerator. Bring to room temperature before serving.",
    ],
  },

  // DESSERT RECIPES (5)
  {
    id: 21,
    title: "Berry Yogurt Parfait",
    description:
      "Layers of creamy yogurt, fresh berries, honey, and granola create a delightful dessert that's both satisfying and nutritious. A lighter alternative to traditional desserts.",
    image: "/placeholder.svg?height=400&width=600&query=berry yogurt parfait dessert",
    heroImage: "/placeholder.svg?height=800&width=1200&query=layered berry yogurt parfait with granola and honey",
    time: "15 mins",
    prepTime: "15 mins",
    cookTime: "0 mins",
    difficulty: "Easy",
    servings: 4,
    tags: ["Dessert", "Pescatarian", "Vegetarian", "No-Cook", "Healthy"],
    ingredients: [
      "3 cups Greek yogurt",
      "2 tablespoons honey, plus more for drizzling",
      "1 teaspoon vanilla extract",
      "2 cups mixed berries (strawberries, blueberries, raspberries)",
      "1 cup granola",
      "2 tablespoons sliced almonds",
      "2 tablespoons shredded coconut (optional)",
      "Fresh mint leaves for garnish (optional)",
    ],
    instructions: [
      "In a bowl, mix Greek yogurt with honey and vanilla extract until well combined.",
      "In serving glasses or bowls, create alternating layers starting with yogurt, then berries, then granola.",
      "Repeat the layers, ending with a layer of berries on top.",
      "Sprinkle with sliced almonds and shredded coconut if using.",
      "Drizzle with additional honey.",
      "Garnish with fresh mint leaves if desired.",
      "Serve immediately or refrigerate for up to 2 hours (add granola just before serving to maintain crunch).",
    ],
  },
  {
    id: 22,
    title: "Lemon Ricotta Cookies",
    description:
      "Soft, cake-like cookies with a delicate lemon flavor and a sweet glaze. The ricotta cheese gives these cookies a moist, tender texture that melts in your mouth.",
    image: "/placeholder.svg?height=400&width=600&query=lemon ricotta cookies",
    heroImage: "/placeholder.svg?height=800&width=1200&query=lemon ricotta cookies with glaze on cooling rack",
    time: "40 mins",
    prepTime: "20 mins",
    cookTime: "20 mins",
    difficulty: "Medium",
    servings: 24,
    tags: ["Dessert", "Pescatarian", "Vegetarian", "Baking", "Italian-Inspired"],
    ingredients: [
      "2 1/2 cups all-purpose flour",
      "1 teaspoon baking powder",
      "1 teaspoon salt",
      "1 cup (2 sticks) unsalted butter, softened",
      "2 cups granulated sugar",
      "2 large eggs",
      "15 oz whole milk ricotta cheese",
      "3 tablespoons lemon juice",
      "Zest of 2 lemons",
      "For the glaze:",
      "1 1/2 cups powdered sugar",
      "3 tablespoons lemon juice",
      "Zest of 1 lemon",
    ],
    instructions: [
      "Preheat oven to 350°F (175°C). Line baking sheets with parchment paper.",
      "In a medium bowl, whisk together flour, baking powder, and salt.",
      "In a large bowl, cream together butter and sugar until light and fluffy, about 3 minutes.",
      "Add eggs one at a time, beating well after each addition.",
      "Mix in ricotta cheese, lemon juice, and lemon zest until combined.",
      "Gradually stir in the dry ingredients until just combined.",
      "Drop rounded tablespoons of dough onto the prepared baking sheets, spacing them about 2 inches apart.",
      "Bake for 15-18 minutes, until the edges are just turning golden.",
      "Allow cookies to cool on the baking sheet for 5 minutes, then transfer to a wire rack to cool completely.",
      "For the glaze, whisk together powdered sugar, lemon juice, and lemon zest until smooth.",
      "Spoon or drizzle the glaze over the cooled cookies and allow it to set before serving.",
    ],
  },
  {
    id: 23,
    title: "Dark Chocolate Dipped Strawberries",
    description:
      "Fresh, juicy strawberries dipped in rich dark chocolate and optionally rolled in various toppings. An elegant, simple dessert that's perfect for special occasions or a romantic treat.",
    image: "/placeholder.svg?height=400&width=600&query=chocolate dipped strawberries",
    heroImage: "/placeholder.svg?height=800&width=1200&query=dark chocolate covered strawberries with toppings",
    time: "30 mins",
    prepTime: "15 mins",
    cookTime: "15 mins",
    difficulty: "Easy",
    servings: 4,
    tags: ["Dessert", "Pescatarian", "Vegetarian", "Chocolate", "Romantic"],
    ingredients: [
      "1 lb fresh strawberries with stems (about 20-24 berries)",
      "8 oz dark chocolate (70% cocoa or higher), chopped",
      "1 tablespoon coconut oil or vegetable shortening",
      "Optional toppings:",
      "1/4 cup finely chopped nuts (pistachios, almonds, or hazelnuts)",
      "1/4 cup shredded coconut",
      "1/4 cup mini chocolate chips",
      "2 oz white chocolate, melted (for drizzling)",
    ],
    instructions: [
      "Wash strawberries and pat completely dry with paper towels. (Important: Chocolate won't adhere properly to wet strawberries.)",
      "Line a baking sheet with parchment paper.",
      "In a microwave-safe bowl, combine dark chocolate and coconut oil. Microwave in 30-second intervals, stirring between each, until completely melted and smooth.",
      "Holding a strawberry by the stem, dip it into the melted chocolate, twisting to coat most of the berry. Allow excess chocolate to drip off.",
      "If using toppings, immediately roll the dipped portion in your chosen topping while the chocolate is still wet.",
      "Place the dipped strawberry on the parchment-lined baking sheet.",
      "Repeat with remaining strawberries.",
      "If using white chocolate drizzle, place melted white chocolate in a small plastic bag, snip off a tiny corner, and drizzle over the dipped strawberries.",
      "Refrigerate for at least 15 minutes or until the chocolate is set.",
      "Serve chilled. Best enjoyed the same day they are made.",
    ],
  },
  {
    id: 24,
    title: "Honey Lavender Panna Cotta",
    description:
      "Silky smooth Italian custard infused with delicate lavender and sweetened with honey. This elegant dessert is surprisingly simple to make and can be prepared ahead of time.",
    image: "/placeholder.svg?height=400&width=600&query=honey lavender panna cotta",
    heroImage: "/placeholder.svg?height=800&width=1200&query=honey lavender panna cotta with berries",
    time: "4 hours 20 mins",
    prepTime: "20 mins",
    cookTime: "0 mins",
    difficulty: "Medium",
    servings: 6,
    tags: ["Dessert", "Pescatarian", "Vegetarian", "Italian", "Make-Ahead"],
    ingredients: [
      "2 cups heavy cream",
      "1 cup whole milk",
      "1/3 cup honey",
      "1 tablespoon dried culinary lavender",
      "1 teaspoon vanilla extract",
      "2 1/2 teaspoons unflavored gelatin",
      "3 tablespoons cold water",
      "Fresh berries for garnish",
      "Additional honey for drizzling",
      "Edible flowers for garnish (optional)",
    ],
    instructions: [
      "In a small bowl, sprinkle gelatin over cold water and let stand for 5 minutes to bloom.",
      "In a saucepan, combine heavy cream, milk, honey, and lavender. Heat over medium heat until it just begins to simmer (do not boil).",
      "Remove from heat, cover, and let steep for 15 minutes.",
      "Strain the mixture through a fine-mesh sieve to remove lavender buds, then return to the saucepan.",
      "Reheat the cream mixture until warm (not boiling).",
      "Add the bloomed gelatin and vanilla extract, stirring until gelatin is completely dissolved.",
      "Pour the mixture into six ramekins or serving glasses.",
      "Refrigerate for at least 4 hours or overnight until set.",
      "To serve, garnish with fresh berries, a drizzle of honey, and edible flowers if desired.",
      "For a more elegant presentation, you can unmold the panna cotta onto serving plates by briefly dipping the ramekins in hot water and inverting onto plates.",
    ],
  },
  {
    id: 25,
    title: "Almond Flour Chocolate Chip Cookies",
    description:
      "Chewy, tender cookies made with almond flour instead of wheat flour. These gluten-free treats are rich with chocolate chips and have a delightful nutty flavor.",
    image: "/placeholder.svg?height=400&width=600&query=almond flour chocolate chip cookies",
    heroImage: "/placeholder.svg?height=800&width=1200&query=gluten free almond flour chocolate chip cookies on rack",
    time: "25 mins",
    prepTime: "10 mins",
    cookTime: "15 mins",
    difficulty: "Easy",
    servings: 18,
    tags: ["Dessert", "Pescatarian", "Vegetarian", "Gluten-Free", "Baking"],
    ingredients: [
      "2 1/2 cups almond flour",
      "1/2 teaspoon baking soda",
      "1/4 teaspoon salt",
      "1/2 cup unsalted butter, softened",
      "1/2 cup brown sugar, packed",
      "1/4 cup granulated sugar",
      "1 large egg",
      "1 teaspoon vanilla extract",
      "1 cup dark chocolate chips",
      "1/2 cup chopped walnuts or pecans (optional)",
      "Flaky sea salt for sprinkling (optional)",
    ],
    instructions: [
      "Preheat oven to 350°F (175°C). Line baking sheets with parchment paper.",
      "In a medium bowl, whisk together almond flour, baking soda, and salt.",
      "In a large bowl, cream together butter, brown sugar, and granulated sugar until light and fluffy.",
      "Beat in the egg and vanilla extract until well combined.",
      "Gradually stir the dry ingredients into the wet ingredients until just combined.",
      "Fold in the chocolate chips and nuts if using.",
      "Drop rounded tablespoons of dough onto the prepared baking sheets, spacing them about 2 inches apart.",
      "Gently flatten each cookie slightly with the palm of your hand (they won't spread as much as traditional cookies).",
      "If desired, sprinkle a small amount of flaky sea salt on top of each cookie.",
      "Bake for 12-15 minutes, until the edges are golden brown.",
      "Allow to cool on the baking sheet for 5 minutes, then transfer to a wire rack to cool completely.",
    ],
  },
]
